/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'case studys',
    },
  ],
};

module.exports = sidebars;
