/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
  productDesign: [{ type: 'autogenerated', dirName: 'case studys' }],
  techWriting: [{ type: 'autogenerated', dirName: 'Tech Writing' }],
  // ... add other directories as needed
};

module.exports = sidebars;
